all: run

run:
	cd expr3 && make all
	cd expr5 && make all
	cd expr6 && make all
	cd expr7 && make all
	cd expr8 && make all
	cd expr9 && make all
	cd expr-ext1 && make all

clean:
	cd expr3 && make clean
	cd expr5 && make clean
	cd expr6 && make clean
	cd expr7 && make clean
	cd expr8 && make clean
	cd expr9 && make clean
	cd expr-ext1 && make clean
	rm -rf ./__pycache__

